import { Router, Response } from 'express';
import { z } from 'zod';
import prisma from '../config/db.js';
import { authenticateJWT, AuthRequest } from '../middleware/auth.js';
import { requireRole } from '../middleware/rbac.js';
import { validateBody } from '../middleware/validate.js';

const router = Router();

const updateStockSchema = z.object({
  quantity: z.number().int().min(0, 'Quantity cannot be negative'),
  reorderThreshold: z.number().int().min(0).optional(),
});

const transferStockSchema = z.object({
  productId: z.number().int().positive(),
  fromWarehouseId: z.number().int().positive(),
  toWarehouseId: z.number().int().positive(),
  quantity: z.number().int().positive('Transfer quantity must be greater than zero'),
});

/**
 * @swagger
 * /api/inventory/view:
 *   get:
 *     summary: Retrieve real-time stock status via PostgreSQL View (v_inventory_stock_status)
 *     tags: [Inventory, DBMS Showcase]
 */
router.get('/view', authenticateJWT, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    // Queries the dedicated PostgreSQL View directly
    const viewRows = await prisma.$queryRaw`
      SELECT * FROM v_inventory_stock_status
      ORDER BY 
        CASE stock_health_status 
          WHEN 'OUT_OF_STOCK' THEN 1 
          WHEN 'LOW_STOCK' THEN 2 
          WHEN 'OVERSTOCKED' THEN 3 
          ELSE 4 
        END, product_name ASC;
    `;

    res.json({
      success: true,
      source: 'PostgreSQL View (v_inventory_stock_status)',
      count: (viewRows as any[]).length,
      data: viewRows,
    });
  } catch (error) {
    console.error('Error querying PostgreSQL View:', error);
    res.status(500).json({ success: false, message: 'Failed to query inventory view' });
  }
});

/**
 * @swagger
 * /api/inventory/alerts:
 *   get:
 *     summary: Get automated stock alerts generated by PostgreSQL Trigger (trg_inventory_low_stock_check)
 *     tags: [Inventory, DBMS Showcase]
 */
router.get('/alerts', authenticateJWT, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const alerts = await prisma.stockAlert.findMany({
      where: { isResolved: false },
      include: {
        product: { select: { id: true, sku: true, name: true, category: true, unitPrice: true } },
        warehouse: { select: { id: true, code: true, name: true, city: true } },
      },
      orderBy: { createdAt: 'desc' },
    });

    res.json({
      success: true,
      source: 'PostgreSQL Trigger Generated Table (stock_alerts)',
      count: alerts.length,
      data: alerts,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch stock alerts' });
  }
});

/**
 * @swagger
 * /api/inventory:
 *   get:
 *     summary: Get inventory items with filter options
 *     tags: [Inventory]
 */
router.get('/', authenticateJWT, async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const warehouseId = req.query.warehouseId ? parseInt(req.query.warehouseId as string, 10) : undefined;
    const category = req.query.category as string | undefined;

    const inventory = await prisma.inventory.findMany({
      where: {
        ...(warehouseId ? { warehouseId } : {}),
        ...(category ? { product: { category } } : {}),
      },
      include: {
        product: true,
        warehouse: true,
      },
      orderBy: { quantity: 'asc' },
    });

    res.json({ success: true, data: inventory });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch inventory' });
  }
});

/**
 * @swagger
 * /api/inventory/{id}/stock:
 *   patch:
 *     summary: Update inventory stock (Triggers PostgreSQL trigger fn_check_inventory_alert)
 *     tags: [Inventory, DBMS Showcase]
 */
router.patch(
  '/:id/stock',
  authenticateJWT,
  requireRole(['ADMIN', 'MANAGER', 'STAFF']),
  validateBody(updateStockSchema),
  async (req: AuthRequest, res: Response): Promise<void> => {
    try {
      const id = parseInt(req.params.id, 10);
      const { quantity, reorderThreshold } = req.body;

      const previous = await prisma.inventory.findUnique({
        where: { id },
        include: { product: true, warehouse: true },
      });

      if (!previous) {
        res.status(404).json({ success: false, message: 'Inventory record not found' });
        return;
      }

      // Update inventory. Note: if quantity <= reorderThreshold, PostgreSQL trigger will automatically fire!
      const updated = await prisma.inventory.update({
        where: { id },
        data: {
          quantity,
          ...(reorderThreshold !== undefined ? { reorderThreshold } : {}),
          lastRestockedAt: quantity > previous.quantity ? new Date() : previous.lastRestockedAt,
        },
        include: { product: true, warehouse: true },
      });

      // Audit log entry
      await prisma.auditLog.create({
        data: {
          userId: req.user!.id,
          action: 'UPDATE_INVENTORY_STOCK',
          tableName: 'inventory',
          recordId: id,
          oldData: { quantity: previous.quantity },
          newData: { quantity: updated.quantity },
        },
      });

      // Check if trigger inserted a new alert for this product & warehouse
      const latestAlert = await prisma.stockAlert.findFirst({
        where: { productId: updated.productId, warehouseId: updated.warehouseId },
        orderBy: { createdAt: 'desc' },
      });

      res.json({
        success: true,
        message: 'Inventory updated successfully.',
        data: updated,
        triggerFired: updated.quantity <= updated.reorderThreshold,
        latestAlert: updated.quantity <= updated.reorderThreshold ? latestAlert : null,
      });
    } catch (error) {
      res.status(500).json({ success: false, message: 'Failed to update inventory' });
    }
  }
);

/**
 * @swagger
 * /api/inventory/transfer:
 *   post:
 *     summary: Atomic stock transfer between warehouses using Prisma Transaction ($transaction)
 *     tags: [Inventory, DBMS Showcase]
 */
router.post(
  '/transfer',
  authenticateJWT,
  requireRole(['ADMIN', 'MANAGER']),
  validateBody(transferStockSchema),
  async (req: AuthRequest, res: Response): Promise<void> => {
    const { productId, fromWarehouseId, toWarehouseId, quantity } = req.body;

    if (fromWarehouseId === toWarehouseId) {
      res.status(400).json({ success: false, message: 'Source and destination warehouses cannot be the same' });
      return;
    }

    try {
      // Execute as ACID transaction
      const result = await prisma.$transaction(async (tx) => {
        const sourceInventory = await tx.inventory.findUnique({
          where: { productId_warehouseId: { productId, warehouseId: fromWarehouseId } },
        });

        if (!sourceInventory || sourceInventory.quantity < quantity) {
          throw new Error(`Insufficient stock in origin warehouse. Available: ${sourceInventory?.quantity ?? 0}, Requested: ${quantity}`);
        }

        // Decrement origin
        const decremented = await tx.inventory.update({
          where: { id: sourceInventory.id },
          data: { quantity: sourceInventory.quantity - quantity },
        });

        // Increment destination
        const destInventory = await tx.inventory.upsert({
          where: { productId_warehouseId: { productId, warehouseId: toWarehouseId } },
          update: { quantity: { increment: quantity } },
          create: {
            productId,
            warehouseId: toWarehouseId,
            quantity: quantity,
            reorderThreshold: 20,
            maxCapacity: 400,
          },
        });

        return { decremented, destInventory };
      });

      res.json({
        success: true,
        message: `Successfully transferred ${quantity} units across warehouses in an atomic transaction.`,
        data: result,
      });
    } catch (error: any) {
      res.status(400).json({ success: false, message: error.message || 'Transfer failed and rolled back' });
    }
  }
);

export default router;
